[package]
name = "everybody_codes_2025"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
log = "0.4.28"
simple_logger = "5.1.0"
utf8-chars = "3.0.5"
